
name: Build Pandoc PDF

on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: report
      - run: |
          mkdir output
      - uses: docker://pandoc/extra
        id: create-pdf
        with:
          args: >-
            -t latex
            --from markdown
            --template /.pandoc/templates/eisvogel.latex
            --toc
            --listings
            --citeproc
            --bibliography=references.bib
            --output=report.pdf
            --csl=university-of-south-wales-harvard.csl
            ./report.md
      - uses: actions/upload-artifact@v4
        id: upload-pdf
        with:
          name: report-output
          path: |
            output/*.pdf
