
name: Build Pandoc PDF

on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir output
      - uses: docker://pandoc/extra
        id: create-pdf
        with:
          args: >-
            -t latex
            --output=output/report.pdf
            --template /.pandoc/templates/eisvogel.latex
            --toc
            --listings
            report/report.md
      - uses: actions/upload-artifact@v4
        id: upload-pdf
        with:
          name: report-output
          path: |
            output/*.pdf

