name: Build Pandoc PDF
on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/extra:edge
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v4
      - name: create pdf file
        id: create-pdf
        run: |
            cd report
            mkdir output
            echo $(ls)
            echo $(pandoc -v)
            pandoc report.md \
              -t latex \
              --from markdown \
              --listings \
              --citeproc \
              --bibliography=references.bib \
              --template /.pandoc/templates/eisvogel.latex \
              --output=output/report.pdf
            echo $(ls output)
      - uses: actions/upload-artifact@v4
        id: upload-pdf
        with:
          name: output
          path: |
            report/output/*.pdf

